"""add_guild_settings

Revision ID: 47c644e9f880
Revises: fafa76d4dbb8
Create Date: 2025-12-09 01:28:30.005850

"""
from alembic import op
import sqlalchemy as sa


revision = '47c644e9f880'
down_revision = 'fafa76d4dbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('prefix', sa.Text(), nullable=True))
    op.add_column('guilds', sa.Column('xp_enabled', sa.Boolean(), nullable=False))
    op.add_column('guilds', sa.Column('xp_rate', sa.Integer(), nullable=False))
    op.add_column('guilds', sa.Column('welcome_enabled', sa.Boolean(), nullable=False))
    op.add_column('guilds', sa.Column('leave_enabled', sa.Boolean(), nullable=False))
    op.add_column('guilds', sa.Column('moderation_log_channel', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'moderation_log_channel')
    op.drop_column('guilds', 'leave_enabled')
    op.drop_column('guilds', 'welcome_enabled')
    op.drop_column('guilds', 'xp_rate')
    op.drop_column('guilds', 'xp_enabled')
    op.drop_column('guilds', 'prefix')
    # ### end Alembic commands ###
